services:
  jekyll:
    image: map9959-site:local
    build: .
    init: true
    command: /srv/jekyll/bin/entry_point.sh
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:35729:35729"
    volumes:
      - .:/srv/jekyll
    environment:
      JEKYLL_ENV: development
